version: "3"
services:
  cassandra:
    build: .
    image: ${SERVICE_IMAGE}:${IMAGE_TAG:-dev}
    command: "cassandra -f"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
      - CASSANDRA_SEEDS=cassandra
    volumes:
      - "cassandra:/var/lib/cassandra"

volumes:
  cassandra:
